# Generated by Django 5.0.7 on 2025-05-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='front_photo',
            field=models.ImageField(blank=True, null=True, upload_to='device_photos/', verbose_name='Foto Frontal'),
        ),
        migrations.AlterField(
            model_name='device',
            name='side_photo',
            field=models.ImageField(blank=True, null=True, upload_to='device_photos/', verbose_name='Foto Lateral'),
        ),
    ]
